# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\uiMenu.ui'
#
# Created: Sat Nov 26 14:12:26 2016
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowMenu(object):
    def setupUi(self, MainWindowMenu):
        MainWindowMenu.setObjectName(_fromUtf8("MainWindowMenu"))
        MainWindowMenu.resize(1024, 724)
        self.centralwidgetMenu = QtGui.QWidget(MainWindowMenu)
        self.centralwidgetMenu.setObjectName(_fromUtf8("centralwidgetMenu"))
        MainWindowMenu.setCentralWidget(self.centralwidgetMenu)
        self.menubar = QtGui.QMenuBar(MainWindowMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindowMenu.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindowMenu)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindowMenu.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindowMenu)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSummary = QtGui.QAction(MainWindowMenu)
        self.actionSummary.setObjectName(_fromUtf8("actionSummary"))
        self.actionUndo = QtGui.QAction(MainWindowMenu)
        self.actionUndo.setEnabled(False)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindowMenu)
        self.actionRedo.setEnabled(False)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCut = QtGui.QAction(MainWindowMenu)
        self.actionCut.setEnabled(False)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindowMenu)
        self.actionCopy.setEnabled(False)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindowMenu)
        self.actionPaste.setEnabled(False)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionDelete = QtGui.QAction(MainWindowMenu)
        self.actionDelete.setEnabled(False)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionSelect_All = QtGui.QAction(MainWindowMenu)
        self.actionSelect_All.setEnabled(False)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionPrint = QtGui.QAction(MainWindowMenu)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionExit = QtGui.QAction(MainWindowMenu)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionEditUsers = QtGui.QAction(MainWindowMenu)
        self.actionEditUsers.setObjectName(_fromUtf8("actionEditUsers"))
        self.actionSelectAwards = QtGui.QAction(MainWindowMenu)
        self.actionSelectAwards.setObjectName(_fromUtf8("actionSelectAwards"))
        self.actionPeriods = QtGui.QAction(MainWindowMenu)
        self.actionPeriods.setObjectName(_fromUtf8("actionPeriods"))
        self.actionAbout = QtGui.QAction(MainWindowMenu)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionTracking = QtGui.QAction(MainWindowMenu)
        self.actionTracking.setObjectName(_fromUtf8("actionTracking"))
        self.actionMakePitMap = QtGui.QAction(MainWindowMenu)
        self.actionMakePitMap.setObjectName(_fromUtf8("actionMakePitMap"))
        self.actionEvents = QtGui.QAction(MainWindowMenu)
        self.actionEvents.setObjectName(_fromUtf8("actionEvents"))
        self.actionPit_map = QtGui.QAction(MainWindowMenu)
        self.actionPit_map.setObjectName(_fromUtf8("actionPit_map"))
        self.actionConfigure = QtGui.QAction(MainWindowMenu)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionJudgeGroups = QtGui.QAction(MainWindowMenu)
        self.actionJudgeGroups.setObjectName(_fromUtf8("actionJudgeGroups"))
        self.actionInspections = QtGui.QAction(MainWindowMenu)
        self.actionInspections.setObjectName(_fromUtf8("actionInspections"))
        self.actionAssignTasks = QtGui.QAction(MainWindowMenu)
        self.actionAssignTasks.setObjectName(_fromUtf8("actionAssignTasks"))
        self.actionUserGroups = QtGui.QAction(MainWindowMenu)
        self.actionUserGroups.setObjectName(_fromUtf8("actionUserGroups"))
        self.actionTouchToTalk = QtGui.QAction(MainWindowMenu)
        self.actionTouchToTalk.setObjectName(_fromUtf8("actionTouchToTalk"))
        self.actionImport_user_list = QtGui.QAction(MainWindowMenu)
        self.actionImport_user_list.setObjectName(_fromUtf8("actionImport_user_list"))
        self.actionImport_match_schedule = QtGui.QAction(MainWindowMenu)
        self.actionImport_match_schedule.setObjectName(_fromUtf8("actionImport_match_schedule"))
        self.actionTeams = QtGui.QAction(MainWindowMenu)
        self.actionTeams.setObjectName(_fromUtf8("actionTeams"))
        self.actionUpload_State = QtGui.QAction(MainWindowMenu)
        self.actionUpload_State.setObjectName(_fromUtf8("actionUpload_State"))
        self.actionMake_fake_match_schedule = QtGui.QAction(MainWindowMenu)
        self.actionMake_fake_match_schedule.setObjectName(_fromUtf8("actionMake_fake_match_schedule"))
        self.actionExport_Match_Notes = QtGui.QAction(MainWindowMenu)
        self.actionExport_Match_Notes.setObjectName(_fromUtf8("actionExport_Match_Notes"))
        self.actionCreateNotificationFor_event = QtGui.QAction(MainWindowMenu)
        self.actionCreateNotificationFor_event.setObjectName(_fromUtf8("actionCreateNotificationFor_event"))
        self.actionMake_SSL_keys = QtGui.QAction(MainWindowMenu)
        self.actionMake_SSL_keys.setObjectName(_fromUtf8("actionMake_SSL_keys"))
        self.actionQR_File = QtGui.QAction(MainWindowMenu)
        self.actionQR_File.setObjectName(_fromUtf8("actionQR_File"))
        self.actionDownload_Updates = QtGui.QAction(MainWindowMenu)
        self.actionDownload_Updates.setObjectName(_fromUtf8("actionDownload_Updates"))
        self.actionErase_match_schedule = QtGui.QAction(MainWindowMenu)
        self.actionErase_match_schedule.setObjectName(_fromUtf8("actionErase_match_schedule"))
        self.actionDeliberation = QtGui.QAction(MainWindowMenu)
        self.actionDeliberation.setObjectName(_fromUtf8("actionDeliberation"))
        self.actionQR_WebPage = QtGui.QAction(MainWindowMenu)
        self.actionQR_WebPage.setObjectName(_fromUtf8("actionQR_WebPage"))
        self.actionExport_Inspections = QtGui.QAction(MainWindowMenu)
        self.actionExport_Inspections.setObjectName(_fromUtf8("actionExport_Inspections"))
        self.actionImport_from_USB = QtGui.QAction(MainWindowMenu)
        self.actionImport_from_USB.setObjectName(_fromUtf8("actionImport_from_USB"))
        self.actionImport_event = QtGui.QAction(MainWindowMenu)
        self.actionImport_event.setObjectName(_fromUtf8("actionImport_event"))
        self.actionImport_new_teams = QtGui.QAction(MainWindowMenu)
        self.actionImport_new_teams.setObjectName(_fromUtf8("actionImport_new_teams"))
        self.actionExport_to_USB = QtGui.QAction(MainWindowMenu)
        self.actionExport_to_USB.setObjectName(_fromUtf8("actionExport_to_USB"))
        self.actionExport_Inspection_Log = QtGui.QAction(MainWindowMenu)
        self.actionExport_Inspection_Log.setObjectName(_fromUtf8("actionExport_Inspection_Log"))
        self.actionTeam_Scores = QtGui.QAction(MainWindowMenu)
        self.actionTeam_Scores.setObjectName(_fromUtf8("actionTeam_Scores"))
        self.actionExport_Team_Notes = QtGui.QAction(MainWindowMenu)
        self.actionExport_Team_Notes.setObjectName(_fromUtf8("actionExport_Team_Notes"))
        self.actionOpen_File = QtGui.QAction(MainWindowMenu)
        self.actionOpen_File.setObjectName(_fromUtf8("actionOpen_File"))
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionConfigure)
        self.menuTools.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindowMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindowMenu)

    def retranslateUi(self, MainWindowMenu):
        MainWindowMenu.setWindowTitle(_translate("MainWindowMenu", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindowMenu", "File", None))
        self.menuEdit.setTitle(_translate("MainWindowMenu", "Edit", None))
        self.menuTools.setTitle(_translate("MainWindowMenu", "Tools", None))
        self.menuHelp.setTitle(_translate("MainWindowMenu", "Help", None))
        self.actionSave.setText(_translate("MainWindowMenu", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindowMenu", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindowMenu", "Ctrl+S", None))
        self.actionSummary.setText(_translate("MainWindowMenu", "Summary Screen", None))
        self.actionUndo.setText(_translate("MainWindowMenu", "Undo", None))
        self.actionUndo.setShortcut(_translate("MainWindowMenu", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("MainWindowMenu", "Redo", None))
        self.actionRedo.setShortcut(_translate("MainWindowMenu", "Ctrl+Y", None))
        self.actionCut.setText(_translate("MainWindowMenu", "Cut", None))
        self.actionCut.setShortcut(_translate("MainWindowMenu", "Ctrl+X", None))
        self.actionCopy.setText(_translate("MainWindowMenu", "Copy", None))
        self.actionCopy.setShortcut(_translate("MainWindowMenu", "Ctrl+C", None))
        self.actionPaste.setText(_translate("MainWindowMenu", "Paste", None))
        self.actionPaste.setShortcut(_translate("MainWindowMenu", "Ctrl+V", None))
        self.actionDelete.setText(_translate("MainWindowMenu", "Delete", None))
        self.actionSelect_All.setText(_translate("MainWindowMenu", "Select All", None))
        self.actionSelect_All.setShortcut(_translate("MainWindowMenu", "Ctrl+A", None))
        self.actionPrint.setText(_translate("MainWindowMenu", "Print...", None))
        self.actionPrint.setShortcut(_translate("MainWindowMenu", "Ctrl+P", None))
        self.actionExit.setText(_translate("MainWindowMenu", "Exit", None))
        self.actionEditUsers.setText(_translate("MainWindowMenu", "Users", None))
        self.actionSelectAwards.setText(_translate("MainWindowMenu", "Awards", None))
        self.actionPeriods.setText(_translate("MainWindowMenu", "Periods", None))
        self.actionAbout.setText(_translate("MainWindowMenu", "About...", None))
        self.actionTracking.setText(_translate("MainWindowMenu", "Judge Tracking", None))
        self.actionMakePitMap.setText(_translate("MainWindowMenu", "Make Pit Map", None))
        self.actionEvents.setText(_translate("MainWindowMenu", "Events", None))
        self.actionPit_map.setText(_translate("MainWindowMenu", "Pit map", None))
        self.actionConfigure.setText(_translate("MainWindowMenu", "Configure", None))
        self.actionJudgeGroups.setText(_translate("MainWindowMenu", "Judge Groups", None))
        self.actionInspections.setText(_translate("MainWindowMenu", "Inspections", None))
        self.actionAssignTasks.setText(_translate("MainWindowMenu", "Assigned tasks", None))
        self.actionUserGroups.setText(_translate("MainWindowMenu", "Channels", None))
        self.actionTouchToTalk.setText(_translate("MainWindowMenu", "Messages", None))
        self.actionImport_user_list.setText(_translate("MainWindowMenu", "Import User List", None))
        self.actionImport_match_schedule.setText(_translate("MainWindowMenu", "Import Match Schedule", None))
        self.actionTeams.setText(_translate("MainWindowMenu", "Teams", None))
        self.actionUpload_State.setText(_translate("MainWindowMenu", "Upload State", None))
        self.actionMake_fake_match_schedule.setText(_translate("MainWindowMenu", "Make fake match schedule", None))
        self.actionExport_Match_Notes.setText(_translate("MainWindowMenu", "Export Match Notes", None))
        self.actionCreateNotificationFor_event.setText(_translate("MainWindowMenu", "Publish Notification", None))
        self.actionMake_SSL_keys.setText(_translate("MainWindowMenu", "Make SSL keys", None))
        self.actionQR_File.setText(_translate("MainWindowMenu", "Tablet Setup QR", None))
        self.actionDownload_Updates.setText(_translate("MainWindowMenu", "Download Updates", None))
        self.actionErase_match_schedule.setText(_translate("MainWindowMenu", "Erase match schedule", None))
        self.actionDeliberation.setText(_translate("MainWindowMenu", "Deliberation", None))
        self.actionQR_WebPage.setText(_translate("MainWindowMenu", "Web Page QR", None))
        self.actionExport_Inspections.setText(_translate("MainWindowMenu", "Export Pit Checklist", None))
        self.actionImport_from_USB.setText(_translate("MainWindowMenu", "Import from Android", None))
        self.actionImport_event.setText(_translate("MainWindowMenu", "Import Teams for Event", None))
        self.actionImport_new_teams.setText(_translate("MainWindowMenu", "Import New Teams", None))
        self.actionExport_to_USB.setText(_translate("MainWindowMenu", "Export State to Android", None))
        self.actionExport_Inspection_Log.setText(_translate("MainWindowMenu", "Export Inspection Log", None))
        self.actionTeam_Scores.setText(_translate("MainWindowMenu", "Team Scores", None))
        self.actionExport_Team_Notes.setText(_translate("MainWindowMenu", "Export Team Notes", None))
        self.actionOpen_File.setText(_translate("MainWindowMenu", "Open File...", None))

